"""
obj_exporter.py

Writes triangle mesh data to a Wavefront OBJ file.

Supports multiple named groups so the renderer can assign different
materials to different parts (e.g. shell vs. beams).

OBJ format written:
  v  x y z          — vertex positions
  g  <name>         — group name (one per mesh part)
  f  i j k          — triangle faces (1-indexed)

Usage (standalone test):
  python obj_exporter.py
"""

import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Core export
# ---------------------------------------------------------------------------

def export_obj(groups: list, output_path: str) -> None:
    """
    Write one or more mesh groups to a single OBJ file.

    Args:
        groups: list of dicts, each with:
                  "name"     : str   — group name (e.g. "shell", "beams")
                  "vertices" : list of (x, y, z) float tuples
                  "faces"    : list of (i, j, k) int tuples — 0-indexed within
                               this group's own vertex list
        output_path: destination file path (created or overwritten).

    The function re-indexes all groups into a single global vertex list so
    faces from different groups don't collide.
    """
    lines = ["# Generated by procedural_engine"]

    # --- write all vertices first, tracking per-group offsets --------------
    offsets = []   # offsets[i] = 1-based index of group i's first vertex
    global_index = 1

    for group in groups:
        offsets.append(global_index)
        for (x, y, z) in group["vertices"]:
            lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
        global_index += len(group["vertices"])

    # --- write faces per group ---------------------------------------------
    for group, offset in zip(groups, offsets):
        lines.append(f"g {group['name']}")
        for (i, j, k) in group["faces"]:
            # OBJ indices are 1-based; add the group's vertex offset
            lines.append(f"f {i+offset} {j+offset} {k+offset}")

    Path(output_path).write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Convenience wrapper used by procedural_engine
# ---------------------------------------------------------------------------

def export_mesh(shell_verts: list, shell_faces: list,
                beam_verts: list,  beam_faces: list,
                output_path: str) -> dict:
    """
    Write shell and beam groups to an OBJ file and return a summary dict.

    Either group may be empty (pass [] for both verts and faces).

    Returns:
        {"vertices": int, "faces": int, "path": str}
    """
    groups = []
    if shell_verts:
        groups.append({"name": "shell", "vertices": shell_verts, "faces": shell_faces})
    if beam_verts:
        groups.append({"name": "beams", "vertices": beam_verts,  "faces": beam_faces})

    export_obj(groups, output_path)

    total_verts = len(shell_verts) + len(beam_verts)
    total_faces = len(shell_faces) + len(beam_faces)
    return {"vertices": total_verts, "faces": total_faces, "path": output_path}


# ---------------------------------------------------------------------------
# Standalone test — hardcoded cube
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    # A unit cube centered at origin, split into two groups to verify
    # that multi-group index offsets work correctly.
    bottom_half = {
        "name": "bottom",
        "vertices": [
            (-1, -1, -1), (1, -1, -1), (1, 1, -1), (-1, 1, -1),
            (-1, -1,  0), (1, -1,  0), (1, 1,  0), (-1, 1,  0),
        ],
        "faces": [
            (0,2,1),(0,3,2),   # bottom face
            (0,1,5),(0,5,4),   # front
            (1,2,6),(1,6,5),   # right
            (2,3,7),(2,7,6),   # back
            (3,0,4),(3,4,7),   # left
            (4,5,6),(4,6,7),   # middle (shared plane)
        ],
    }
    top_half = {
        "name": "top",
        "vertices": [
            (-1, -1,  0), (1, -1,  0), (1, 1,  0), (-1, 1,  0),
            (-1, -1,  1), (1, -1,  1), (1, 1,  1), (-1, 1,  1),
        ],
        "faces": [
            (0,1,5),(0,5,4),
            (1,2,6),(1,6,5),
            (2,3,7),(2,7,6),
            (3,0,4),(3,4,7),
            (4,5,6),(4,6,7),   # top face
        ],
    }

    out = "test_cube.obj"
    export_obj([bottom_half, top_half], out)

    # Verify the file
    text = Path(out).read_text()
    v_lines = [l for l in text.splitlines() if l.startswith("v ")]
    f_lines = [l for l in text.splitlines() if l.startswith("f ")]
    g_lines = [l for l in text.splitlines() if l.startswith("g ")]

    print(f"Written to: {out}")
    print(f"  Vertex lines : {len(v_lines)}  (expected 16)")
    print(f"  Face lines   : {len(f_lines)}  (expected 22)")
    print(f"  Groups       : {[l.split()[1] for l in g_lines]}")

    # Check that no face references an out-of-range index
    total_verts = len(v_lines)
    errors = 0
    for l in f_lines:
        for idx in [int(x) for x in l.split()[1:]]:
            if not (1 <= idx <= total_verts):
                print(f"  ERROR: index {idx} out of range [1, {total_verts}]")
                errors += 1
    if errors == 0:
        print("  All face indices valid.")

    # Clean up test file
    Path(out).unlink()
    print("  Test file removed.")
